{% set name = "zulip" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zulip-{{ version }}.tar.gz
  sha256: 7a14149e5d9e3fcc53b13e998719fd1f6ccb8289bc60fccbaa1aafcd0a9d0843

build:
  entry_points:
    - zulip-send=zulip.send:main
    - zulip-api-examples=zulip.api_examples:main
    - zulip-matrix-bridge=integrations.bridge_with_matrix.matrix_bridge:main
    - zulip-api=zulip.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - distro
    - matrix-nio
    - python >=3.8
    - requests >=0.12.1
    - typing-extensions >=4.5.0

test:
  imports:
    - integrations
    - zulip
  commands:
    - pip list
    - pip check
    - zulip-send --help
    - zulip-api-examples --help
    - zulip-matrix-bridge --help
    # - zulip-api --help
  requires:
    - pip

about:
  home: https://pypi.org/project/zulip
  summary: Bindings for the Zulip message API
  license: MIT
  license_file: integrations/perforce/license.txt
  dev_url: https://github.com/zulip/python-zulip-api

extra:
  recipe-maintainers:
    - goanpeca
