{% set name = "zulip" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zulip-{{ version }}.tar.gz
  sha256: 7e3d5097feb22e912dda187cdabdebf5b2022cba95b32a43793e27abe9c52e6f

build:
  entry_points:
    - zulip-send=zulip.send:main
    - zulip-api-examples=zulip.api_examples:main
    - zulip-matrix-bridge=integrations.bridge_with_matrix.matrix_bridge:main
    - zulip-api=zulip.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - distro
    - matrix_client
    - python >=3.6
    - requests >=0.12.1
    - typing-extensions >=3.7

test:
  imports:
    - integrations
    - zulip
  commands:
    - pip list
    - pip check
    - zulip-send --help
    - zulip-api-examples --help
    - zulip-matrix-bridge --help
    # - zulip-api --help
  requires:
    - pip

about:
  home: https://www.zulip.org/
  summary: Bindings for the Zulip message API
  dev_url: https://github.com/zulip/python-zulip-api/
  license: MIT
  license_file: integrations/perforce/license.txt

extra:
  recipe-maintainers:
    - goanpeca
